// Fake data for demonstration purposes
export const fakeAssociations = [
  {
    _id: "1",
    name: "Clean Water Initiative",
    logo: "/favicon.png?height=100&width=100",
    description:
      "Providing clean water access to underserved communities worldwide through innovative solutions and sustainable infrastructure development. Our mission is to ensure every person has access to safe, clean drinking water.",
    category: "social",
    city: "New York",
    status: "approved",
    email: "contact@cleanwater.org",
    phone: "+1 (555) 123-4567",
    address: "123 Water Street",
    postalCode: "10001",
    country: "United States",
    website: "https://cleanwater.org",
    members: 150,
    createdAt: new Date("2023-01-15"),
  },
  {
    _id: "2",
    name: "Youth Sports Academy",
    logo: "/favicon.png?height=100&width=100",
    description:
      "Empowering young athletes through comprehensive sports training and mentorship programs. Building character through sports excellence and providing opportunities for underprivileged youth.",
    category: "sports",
    city: "Los Angeles",
    status: "approved",
    email: "info@youthsports.org",
    phone: "+1 (555) 987-6543",
    address: "456 Sports Avenue",
    postalCode: "90210",
    country: "United States",
    website: "https://youthsports.org",
    members: 85,
    createdAt: new Date("2023-02-20"),
  },
  {
    _id: "3",
    name: "Cultural Heritage Foundation",
    logo: "/favicon.png?height=100&width=100",
    description:
      "Preserving and promoting cultural heritage through art, music, and educational programs. Connecting communities with their roots and fostering cultural understanding across generations.",
    category: "cultural",
    city: "Chicago",
    status: "approved",
    email: "hello@culturalheritage.org",
    phone: "+1 (555) 456-7890",
    address: "789 Heritage Lane",
    postalCode: "60601",
    country: "United States",
    website: "https://culturalheritage.org",
    members: 120,
    createdAt: new Date("2023-03-10"),
  },
  {
    _id: "4",
    name: "Education for All",
    logo: "/favicon.png?height=100&width=100",
    description:
      "Breaking barriers to education by providing resources and support to underprivileged students. Every child deserves quality education regardless of their economic background or location.",
    category: "education",
    city: "Houston",
    status: "approved",
    email: "support@educationforall.org",
    phone: "+1 (555) 321-0987",
    address: "321 Learning Street",
    postalCode: "77001",
    country: "United States",
    website: "https://educationforall.org",
    members: 200,
    createdAt: new Date("2023-04-05"),
  },
  {
    _id: "5",
    name: "Green Earth Project",
    logo: "/favicon.png?height=100&width=100",
    description:
      "Fighting climate change through reforestation and environmental education initiatives. Creating a sustainable future for all through community-driven environmental action and awareness programs.",
    category: "environment",
    city: "Seattle",
    status: "approved",
    email: "contact@greenearth.org",
    phone: "+1 (555) 654-3210",
    address: "654 Green Way",
    postalCode: "98101",
    country: "United States",
    website: "https://greenearth.org",
    members: 95,
    createdAt: new Date("2023-05-12"),
  },
  {
    _id: "6",
    name: "Health Care Heroes",
    logo: "/favicon.png?height=100&width=100",
    description:
      "Providing medical care and health education to remote and underserved areas. Health is a fundamental human right, and we work tirelessly to ensure everyone has access to quality healthcare.",
    category: "health",
    city: "Miami",
    status: "approved",
    email: "info@healthcareheroes.org",
    phone: "+1 (555) 789-0123",
    address: "987 Health Plaza",
    postalCode: "33101",
    country: "United States",
    website: "https://healthcareheroes.org",
    members: 175,
    createdAt: new Date("2023-06-18"),
  },
  {
    _id: "7",
    name: "Digital Literacy Foundation",
    logo: "/favicon.png?height=100&width=100",
    description:
      "Bridging the digital divide by providing technology education and resources to underserved communities. Empowering people with digital skills for the modern world.",
    category: "education",
    city: "Austin",
    status: "approved",
    email: "hello@digitalliteracy.org",
    phone: "+1 (555) 147-2580",
    address: "147 Tech Boulevard",
    postalCode: "73301",
    country: "United States",
    website: "https://digitalliteracy.org",
    members: 65,
    createdAt: new Date("2023-07-22"),
  },
  {
    _id: "8",
    name: "Community Food Network",
    logo: "/favicon.png?height=100&width=100",
    description:
      "Combating hunger and food insecurity through food banks, nutrition education, and sustainable agriculture programs. No one should go hungry in our communities.",
    category: "social",
    city: "Denver",
    status: "approved",
    email: "contact@communityfood.org",
    phone: "+1 (555) 369-2580",
    address: "369 Food Street",
    postalCode: "80201",
    country: "United States",
    website: "https://communityfood.org",
    members: 110,
    createdAt: new Date("2023-08-14"),
  },
]
